### ISSUE TITLE
Wouldn't accept import statement.

### ISSUE THREAD

**Issue by pajohns** [kavil/ng2SmoothScroll#7]
Your documentation on the npm website states to use the import statement:
import { SmoothScrollToDirective, SmoothScrollDirective } from "ng2SmoothScroll";
however this was highlighted as a missing package. Used "ng2-smooth-scroll" and worked fine.

**Comment by iryna-babrouskaya** [comment]
As @pajohns wrote, the current import from the documentation is not working
Also, for the Angular 5 version, the import "ng2-smooth-scroll" brings an error:
```
Module build failed: Error: %project_path%\node_modules\ng2-smooth-scroll\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (%project_path%\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (%project_path%\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```
